name: Return of The Muses
favicon: null
layout_spectrum: 0.68048
typography_spectrum: 0.19452
title: 'a London-based production company for film, music and literature '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#ffffff'
    - '#4f4200'
    - '#b0c800'
    - '#00c100'
  brandStrength: 0.375
  lightness: 0.3678037680219859
  saturation: 0.5
  rhythmicContrast: 0.9542752732522786
purpose: []
