name: Return of the Muses
favicon: null
layout_spectrum: 0.27891565626487136
typography_spectrum: 0.2493
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#4e4e4e'
    - '#8d8d8d'
    - '#c7c7c7'
    - '#fbfbfb'
  brandStrength: 0.28653337503783405
  lightness: 0.3678037680219859
  saturation: 0.47409884724766016
  rhythmicContrast: 0.9542752732522786
purpose: []
