name: Return of the Muses
favicon: null
layout_spectrum: 0.27891565626487136
typography_spectrum: 0.8730096805375069
title: This is the home of Return of the Muses Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#353535'
    - '#0d0d0d'
    - '#979797'
    - '#cccccc'
  brandStrength: 0.28653337503783405
  lightness: 0.3678037680219859
  saturation: 0.47409884724766016
  rhythmicContrast: 0.9542752732522786
purpose: []
