name: Return of the Muses
favicon: null
layout_spectrum: 0.27891565626487136
typography_spectrum: 0.2493
title: This is the home of Return of the Muses Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e5f3fe'
    - '#004466'
    - '#0097fd'
    - '#9bd2fd'
  brandStrength: 0.28653337503783405
  lightness: 0.3678037680219859
  saturation: 0.47409884724766016
  rhythmicContrast: 0.9542752732522786
purpose: []
